[package]
name = "sage"
version = "0.4.7"
description = "Sage Desktop App"
authors = ["Juan Castañeda", "Nel Alejandro Mora", "Vilma Tirado Gomez"]
repository = "https://github.com/SageWizards/Sage-Desktop"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
tauri = { version = "1.2", features = ["dialog-confirm", "dialog-message", "dialog-save", "fs-all", "global-shortcut-all", "macos-private-api", "os-all", "path-all", "shell-open", "system-tray", "updater", "window-all"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tauri-plugin-positioner = { version = "1.0.4", features = ["system-tray"] }
tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }

[features]
custom-protocol = ["tauri/custom-protocol"]
