export interface IUniversity {
    name: string
    url: string
    country: 'colombia' | 'mexico'
    programs: string[]
}

export const universitiesColombia: IUniversity[] = [
    {
        name: 'Universidad Nacional de Colombia', 
        url: '/assets/imgs/', 
        country: 'colombia', 
        programs: [
            "Arquitectura", 
            "Artes Plásticas",
            "Cine y Televisión",  
            "Diseño Gráfico",
            "Diseño Industrial", 
            "Música", 
            "Música Instrumental", 
            "Ingeniería Agronoma", 
            "Ingeniería Agricola",
            "Ingeniería Civil",
            "Ingeniería Industrial",
            "Ingeniería Electrónica",
            "Ingeniería Electrica",
            "Ingeniería Mecánica",   
            "Ingeniería de Sistemas y Computación", 
            "Ingeniería Mecátronica",
            "Ingeniería Química",  
            "Biología", 
            "Estadística", 
            "Farmacia", 
            "Física", 
            "Geología", 
            "Ciencias de la Computación", 
            "Matemáticas", 
            "Química", 
            "Administración de Empresas", 
            "Contaduría Pública", 
            "Economía", 
            "Antropología", 
            "Español y Filología Clásica", 
            "Estudios Literarios", 
            "Filología e idiomas", 
            "Filosofía", 
            "Historia", 
            "Geografía", 
            "Lingüística", 
            "Psicología", 
            "Enfermería", 
            "Sociología", 
            "Ciencias Políticas", 
            "Trabajo Social", 
            "Derecho", 
            "Fisioterapia", 
            "Fonoaudiología", 
            "Nutrición y Dietética",
            "Medicina",
            "Terapia Ocupacional", 
            "Medicina Veterinaria", 
            "Zootecnia", 
            "Odontología"
        ]
    }, {
        name: 'Universidad de los Andes', 
        url: '/assets/imgs/', 
        country: 'colombia', 
        programs: [
            "Estudios Dirigidos", 
            "Administración", 
            "Economía", 
            "Gobierno y Asuntos Públicos", 
            "Biologia", 
            "Física", 
            "Geociencias", 
            "Matemáticas", 
            "Microbiologia", 
            "Química", 
            "Medicina", 
            "Arquitectura", 
            "Arte", 
            "Historia del Arte", 
            "Diseño", 
            "Literatura", 
            "Música", 
            "Narrativas Digitales", 
            "Ingeniería Ambiental", 
            "Ingeniería Biomédica", 
            "Ingeniería Civil", 
            "Ingeniería Electrónica", 
            "Ingeniería Industrial", 
            "Ingeniería Mecánica", 
            "Ingeniería Química", 
            "Ingeniería de Sistemas y Computación", 
            "Derecho",
            "Antropologia",
            "Estudios Globales",
            "Filosofía",
            "Historia",
            "Lenguas y Cultura",
            "Psicología",     
            "Licenciatura en Educación Infantil", 
            "Licenciatura en Artes", 
            "Licenciatura en Biologia", 
            "Licenciatura en Español y Filosofía", 
            "Licenciatura en Filosofía", 
            "Licenciatura en Física", 
            "Licenciatura en Historia", 
            "Licenciatura en Matemáticas", 
            "Licenciatura en Quimica"
        ]
    }, {
        name: 'Universidad Externado de Colombia', 
        url: '/assets/imgs/', 
        country: 'colombia', 
        programs: []
    }, {
        name: 'Universidad Santo Tomas', 
        url: '/assets/imgs/', 
        country: 'colombia', 
        programs: []
    }, {
        name: 'Pontificia Universidad Javeriana', 
        url: '/assets/imgs/', 
        country: 'colombia', 
        programs: [
            "Arquitectura", 
            "Diseño Industrial", 
            "Artes Escénicas", 
            "Estudios Musicales", 
            "Artes Visuales", 
            "Bacteriología", 
            "Biología",
            "Ciencia de Datos",
            "Matemáticas", 
            "Nutrición y Dietética", 
            "Microbiología Industrial", 
            "Química Farmacéutica",
            "Administración de Empresas", 
            "Contaduría Pública", 
            "Economía", 
            "Finanzas", 
            "Negocios internacionales", 
            "Derecho", 
            "Antropología", 
            "Estudios Literarios", 
            "Historia", 
            "Sociología", 
            "Ciencia Política", 
            "Relaciones Internacionales", 
            "Ciencia de la Información, Bibliotecología y Archivística", 
            "Comunicación Social", 
            "Licenciatura en Lenguas Modernas con Énfasis en Inglés y Francés", 
            "Licenciatura en Ciencias Naturales y Educación Ambiental", 
            "Licenciatura en Educación Física", 
            "Licenciatura en Educación Infantil",
            "Licenciatura en Filosofía", 
            "Licenciatura en Literatura y Lengua Castellana", 
            "Enfermería", 
            "Ecología", 
            "Filosofía", 
            "Bioingeniería", 
            "Ingeniería Civil", 
            "Ingeniería Electrónica", 
            "Ingeniería Industrial", 
            "Ingeniería Mecánica", 
            "Ingeniería Mecatrónica", 
            "Ingeniería en Redes y Telecomunicaciones", 
            "Ingeniería de Sistemas", 
            "Medicina", 
            "Odontología", 
            "Psicología", 
            "Odontología", 
            "Psicología", 
            "Teología", 
            "Licenciatura en Teología" 
        ]
    }, {
        name: 'Universidad Central', 
        url: '/assets/imgs/', 
        country: 'colombia', 
        programs: []
    }, {
        name: 'Universidad de La Salle', 
        url: '/assets/imgs/', 
        country: 'colombia', 
        programs: []
    }, {
        name: 'Universidad ECCI', 
        url: '/assets/imgs/', 
        country: 'colombia', 
        programs: []
    }
]


